<?php
// login_2fa.php
// 2FA Verification Page during Login Flow
session_start();
require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/totp_helper.php';

if (!isset($_SESSION['2fa_pending_user'])) {
    header("Location: /login.php");
    exit;
}

$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $totpCode = trim($_POST['totp_code'] ?? '');
    $pendingUser = $_SESSION['2fa_pending_user'];

    if (verify_totp_code($pendingUser['two_factor_secret'], $totpCode)) {
        // Complete Authentication
        $_SESSION['user_id']   = $pendingUser['id'];
        $_SESSION['username']  = $pendingUser['username'];
        $_SESSION['user_role'] = $pendingUser['role'];
        $_SESSION['user_email']= $pendingUser['email'];

        unset($_SESSION['2fa_pending_user']);

        // Redirect based on role
        if (in_array($pendingUser['role'], ['admin', 'agent'], true)) {
            header("Location: /admin/dashboard.php");
        } else {
            header("Location: /index.php");
        }
        exit;
    } else {
        $error = 'Invalid 2FA code. Please try again.';
    }
}

require_once __DIR__ . '/includes/header.php';
?>

<main class="container my-5" style="max-width: 450px;">
    <div class="card shadow-sm">
        <div class="card-header bg-dark text-white text-center">
            <h4 class="m-0"><i class="fa-solid fa-shield-halved me-2"></i> Two-Factor Verification</h4>
        </div>
        <div class="card-body">
            <p class="text-muted text-center">Enter the 6-digit code generated by your Authenticator app.</p>

            <?php if ($error): ?><div class="alert alert-danger py-2"><?php echo htmlspecialchars($error); ?></div><?php endif; ?>

            <form method="POST" action="login_2fa.php">
                <div class="mb-3">
                    <input type="text" name="totp_code" class="form-control form-control-lg text-center letter-spacing" placeholder="000000" maxlength="6" autofocus required autocomplete="off">
                </div>
                <button type="submit" class="btn btn-primary w-100 btn-lg"><i class="fa-solid fa-key me-1"></i> Verify Code</button>
            </form>
        </div>
    </div>
</main>

<?php require_once __DIR__ . '/includes/footer.php'; ?>